const URL_MOMENTUM = '/static/images/Momentum';
const URL_LEAD = '/static/images/Lead';

export const momentumImages = [
  {
    src: `${URL_MOMENTUM}/Cambridge I.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - Cambridge I',
    thumbnail: '',
    caption: 'Cambridge I - C-type print, 117 x 290 cm, 2011',
  },
  {
    src: `${URL_MOMENTUM}/Cambridge IV.jpg`,
    width: 3,
    height: 4,
    alt: 'Alejandro Guijarro - Cambridge IV',
    thumbnail: '',
    caption: 'Cambridge IV - C-type print, 119 x 300 cm, 2011',
  },
  {
    src: `${URL_MOMENTUM}/Oxford II.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - Oxford II',
    thumbnail: '',
    caption: 'Oxford II - C-type print, 110 x 150 cm, 2011',
  },
  {
    src: `${URL_MOMENTUM}/Cambridge V.jpg`,
    width: 3,
    height: 4,
    alt: 'Alejandro Guijarro - Cambridge V',
    thumbnail: '',
    caption: 'Cambridge V - C-type print, 117 x 200cm, 2011',
  },
  {
    src: `${URL_MOMENTUM}/Artipelag 1.jpg`,
    width: 1,
    height: 1,
    alt: 'Alejandro Guijarro - Artipelag Konsthall 2014',
    thumbnail: '',
    caption: 'Installation View - Artipelag Konsthall, Stockholm, 2014',
  },
  {
    src: `${URL_MOMENTUM}/CERN I.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - CERN I',
    thumbnail: '',
    caption: 'CERN I - C-type print, 100 x 180 cm, 2012',
  },
  {
    src: `${URL_MOMENTUM}/CERN II.jpg`,
    width: 3,
    height: 4,
    alt: 'Alejandro Guijarro - CERN II',
    thumbnail: '',
    caption: 'CERN II - C-type print, 100 x 180 cm, 2012',
  },
  {
    src: `${URL_MOMENTUM}/Harvard I.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - Harvard I',
    thumbnail: '',
    caption: 'Harvard I - C-type print, 160 x 122 cm, 2014',
  },
  {
    src: `${URL_MOMENTUM}/SLAC-IV.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - SLAC IV',
    thumbnail: '',
    caption: 'SLAC IV - C-type print, 117 x 243 cm, 2012',
  },
  {
    src: `${URL_MOMENTUM}/LIMS I.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - LIMS I',
    thumbnail: '',
    caption: 'LIMS I - C-type print, 117 x 350 cm, 2015',
  },
  {
    src: `${URL_MOMENTUM}/MIT III.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - MIT III',
    thumbnail: '',
    caption: 'MIT III - C-type print, 112 x 183 cm, 2014',
  },
  {
    src: `${URL_MOMENTUM}/Oxford I.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - Oxford I',
    thumbnail: '',
    caption: 'Oxford I - C-type print, 110 x 150 cm, 2011',
  },
  {
    src: `${URL_MOMENTUM}/7_tristan-hoare.jpg`,
    width: 4,
    height: 3,
    alt: 'Installation View - Tristan Hoare, London, 2012',
    thumbnail: '',
    caption: 'Installation View - Tristan Hoare, London, 2012',
  },
  {
    src: `${URL_MOMENTUM}/Cambridge III.jpg`,
    width: 3,
    height: 4,
    alt: 'Alejandro Guijarro - Cambridge III',
    thumbnail: '',
    caption: 'Cambridge III - C-type print, 100 x 101 cm, 2011',
  },
  {
    src: `${URL_MOMENTUM}/SLAC III.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - SLAC III',
    thumbnail: '',
    caption: 'SLAC III - C-type print, 117 x 180 cm, 2012',
  },
  {
    src: `${URL_MOMENTUM}/Galerie-Huit.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - Installation View - Galerie Huit',
    thumbnail: '',
    caption: 'Installation View - Galerie Huit, Hong Kong, 2017',
  },
  {
    src: `${URL_MOMENTUM}/Stanford III.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - Stanford III',
    thumbnail: '',
    caption: 'Stanford III - C-type print, 117 x 240 cm, 2012',
  },
  {
    src: `${URL_MOMENTUM}/7_saatchi-install.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - Installation View - Saatchi Gallery',
    thumbnail: '',
    caption: 'Installation View - Saatchi Gallery, London, 2014',
  },
  {
    src: `${URL_MOMENTUM}/UC Berkeley II.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - UC Berkeley II',
    thumbnail: '',
    caption: 'UC Berkeley II - C-type print, 112 x 236 cm, 2012',
  },
  {
    src: `${URL_MOMENTUM}/Stanford II.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - Stanford II',
    thumbnail: '',
    caption: 'Stanford II - C-type print, 174 x 113 cm, 2012',
  },
  {
    src: `${URL_MOMENTUM}/UC Berkeley IV.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - UC Berkeley IV',
    thumbnail: '',
    caption: 'UC Berkeley IV - C-type print, 114 x 180 cm, 2012',
  },
  {
    src: `${URL_MOMENTUM}/Cambridge II.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - Cambridge II',
    thumbnail: '',
    caption: 'Cambridge II - C-type print, 117 x 200 cm, 2011',
  },
  {
    src: `${URL_MOMENTUM}/UC Berkeley V.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - UC Berkeley V',
    thumbnail: '',
    caption: 'UC Berkeley V - C-type print, 118 x 236 cm, 2012',
  },
  {
    src: `${URL_MOMENTUM}/Stanford I.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - Stanford I',
    thumbnail: '',
    caption: 'Stanford I - C-type print, 117 x 240 cm, 2012',
  },
];

export const leadImages = [
  {
    src: `${URL_LEAD}/P01692a00xf2006 (Adam and Eve).jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - P01692a00xf2006 (Adam and Eve)',
    thumbnail: '',
    caption:
      'P01692a00xf2006 (Adam and Eve) - Archival Pigment Print, 242 x 184.5 cm, 2016',
  },
  {
    src: `${URL_LEAD}/P01180a00xf2011 (Prince Baltasar Carlos on Horseback).jpg`,
    width: 4,
    height: 3,
    alt:
      'Alejandro Guijarro - P01180a00xf2011 (Prince Baltasar Carlos on Horseback)',
    thumbnail: '',
    caption:
      'P01180a00xf2011 (Prince Baltasar Carlos on Horseback) - Archival Pigment Print, 177 x 211 cm, 2016',
  },
  {
    src: `${URL_LEAD}/Installation-View-Tristan-Hoare-I.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - Installation View, Tristan Hoare, London, 2017',
    thumbnail: '',
    caption: 'Installation View - Tristan Hoare, London, 2017',
  },
  {
    src: `${URL_LEAD}/20769 (Descent from the cross).jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - 20769 (Descent from the cross)',
    thumbnail: '',
    caption:
      '20769 (Descent from the cross) - Archival Pigment Print, 100 x 77 cm, 2016',
  },
  {
    src: `${URL_LEAD}/21600 (St Gregory the Great).jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - 21600 (St Gregory the Great)',
    thumbnail: '',
    caption:
      '21600 (St Gregory the Great) - Archival Pigment Print, 60 x 60 cm, 2016',
  },
  {
    src: `${URL_LEAD}/15816 (St Gregory the Great).jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - 15816 (St Gregory the Great)',
    thumbnail: '',
    caption:
      '15816 (St Gregory the Great) - Archival Pigment Print, 60 x 60 cm, 2016',
  },
  {
    src: `${URL_LEAD}/49757 (St Gregory the Great).jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - 49757 (St Gregory the Great)',
    thumbnail: '',
    caption:
      '49757 (St Gregory the Great) - Archival Pigment Print, 60 x 60 cm, 2016',
  },
  {
    src: `${URL_LEAD}/57954 (Saint Pierre Released From Prison).jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - 57954 (Saint Pierre Released From Prison)',
    thumbnail: '',
    caption:
      '57954 (Saint Pierre Released From Prison) - Archival Pigment Print, 48.5 x 64.5 cm, 2016',
  },
  {
    src: `${URL_LEAD}/P01627a00xf2013 (Inmaculate Conception).jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - P01627a00xf2013 (Inmaculate Conception)',
    thumbnail: '',
    caption:
      'P01627a00xf2013 (Inmaculate Conception) - Archival Pigment Print, 200 x 134 cm, 2016',
  },
  {
    src: `${URL_LEAD}/73813 (Siege of Beauvais in 1472).jpg`,
    width: 3,
    height: 4,
    alt: 'Alejandro Guijarro - 73813 (Siege of Beauvais in 1472)',
    thumbnail: '',
    caption:
      '73813 (Siege of Beauvais in 1472) - Archival Pigment Print, 84 x 105 cm, 2016',
  },
  {
    src: `${URL_LEAD}/N-0583-00-000135 (The Battle of San Romano).jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - N-0583-00-000135 (The Battle of San Romano)',
    thumbnail: '',
    caption:
      'N-0583-00-000135 (The Battle of San Romano) - Archival Pigment Print, 180 x 320 cm, 2016',
  },
  {
    src: `${URL_LEAD}/P01637a00xf2012 (The Brazen Serpent).jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - P01637a00xf2012 (The Brazen Serpent)',
    thumbnail: '',
    caption:
      'P01637a00xf2012 (The Brazen Serpent) - Archival Pigment Print, 207 x 234 cm, 2016',
  },
  {
    src: `${URL_LEAD}/P01915a00xf2008 (The Annunciation).jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - P01915a00xf2008 (The Annunciation)',
    thumbnail: '',
    caption:
      'P01915a00xf2008 (The Annunciation) - Archival Pigment Print, 70 x 78 cm, 2016',
  },
  {
    src: `${URL_LEAD}/Installation-View-Tristan-Hoare-II.jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - Installation View - Tristan Hoare, London, 2017',
    thumbnail: '',
    caption: 'Installation View - Tristan Hoare, London, 2017',
  },
  {
    src: `${URL_LEAD}/P07767a00xf2011 (The Countess of Chinchon).jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - P07767a00xf2011 (The Countess of Chinchon)',
    thumbnail: '',
    caption:
      'P07767a00xf2011 (The Countess of Chinchon) - Archival Pigment Print, 216 x 143 cm, 2016',
  },
  {
    src: `${URL_LEAD}/19207 (Boissy d'Anglas at the National Convention [20 May 1795]).jpg`,
    width: 4,
    height: 3,
    alt:
      'Alejandro Guijarro - 19207 (Boissy d`Anglas at the National Convention [20 May 1795])',
    thumbnail: '',
    caption:
      '19207 (Boissy d`Anglas at the National Convention [20 May 1795]) - Archival Pigment Print, 79 x 104 cm, 2016',
  },
  {
    src: `${URL_LEAD}/RX3000 (Michelangelo, Painter, Sculptor and Architect).jpg`,
    width: 4,
    height: 3,
    alt:
      'Alejandro Guijarro - RX3000 (Michelangelo, Painter, Sculptor and Architect)',
    thumbnail: '',
    caption:
      'RX3000 (Michelangelo, Painter, Sculptor and Architect) - Archival Pigment Print, 40 x 49 cm, 2016',
  },
  {
    src: `${URL_LEAD}/RX15259 (The Bed of Justice held in Parliament by a majority of Louis XV [February 22, 1723]).jpg`,
    width: 4,
    height: 3,
    alt:
      'Alejandro Guijarro - RX15259 (The Bed of Justice held in Parliament by a majority of Louis XV [February 22, 1723])',
    thumbnail: '',
    caption:
      'RX15259 (The Bed of Justice held in Parliament by a majority of Louis XV [February 22, 1723]) - Archival Pigment Print, 56 x 82 cm, 2016',
  },
  {
    src: `${URL_LEAD}/RX15260 (The Bestowal of the Order of Saint-Spirit, in the chapel of Versailles Palace [3 June 1724]).jpg`,
    width: 4,
    height: 3,
    alt:
      'Alejandro Guijarro - RX15260 (The Bestowal of the Order of Saint-Spirit, in the chapel of Versailles Palace [3 June 1724])',
    thumbnail: '',
    caption:
      'RX15260 (The Bestowal of the Order of Saint-Spirit, in the chapel of Versailles Palace [3 June 1724]) - Archival Pigment Print, 56 x 82 cm, 2016',
  },
  {
    src: `${URL_LEAD}/RX15088 (Mona Lisa).jpg`,
    width: 4,
    height: 3,
    alt: 'Alejandro Guijarro - RX15088 (Mona Lisa)',
    thumbnail: '',
    caption: 'RX15088 (Mona Lisa) - Archival Pigment Print, 77 x 53 cm, 2016',
  },
];
